name: "Coding Standards"

on:
  pull_request:
    branches:
      - "*.x"
  push:
    branches:
      - "*.x"
  schedule:
    # Run workflow on every Sunday
    - cron: '25 5 * * 0'
  workflow_dispatch:

jobs:
  coding-standards:
    name: "Coding Standards"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.1"

      - name: "Cache dependencies installed with Composer"
        uses: "actions/cache@v4"
        with:
          path: "~/.composer/cache"
          key: "php-composer-locked-${{ hashFiles('composer.json') }}"
          restore-keys: "php-composer-normal-"

      - name: "Install dependencies with Composer"
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: "Run PHP-CS-Fixer"
        run: "vendor/bin/php-cs-fixer check -v"
